name: Empty Commit Trigger
on:
  workflow_dispatch:
jobs:
  daily-empty-commit:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Create empty commit
        run: |
          git commit --allow-empty -m "trigger daily deploy"
          git push origin ${{ github.ref }}
